name: godot-ci

on:
  push:
    branches: [ main ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export game
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Godot Export
        id: export
        uses: abarichello/godot-ci@v1
        with:
          godot_version: 4.6.1
          export_template_version: 4.6.1
          relative_project_path: ./

      - name: Create Release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
